steps:
- name: node:18-bullseye
  entrypoint: npm
  args: ['ci']
  id: Install
- name: node:18-bullseye
  entrypoint: npm
  args: ['test']
  id: Test
- name: docker:20
  args: ['build', '--no-cache', '-t', 'europe-north1-docker.pkg.dev/$PROJECT_ID/images/api:$SHORT_SHA', '.']
  id: Build
- name: docker:20
  args: ['push', 'europe-north1-docker.pkg.dev/$PROJECT_ID/images/api:$SHORT_SHA']
  id: Push
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: gcloud
  args: ['run', 'deploy', '$_SERVICE_NAME', '--image', 'europe-north1-docker.pkg.dev/$PROJECT_ID/images/api:$SHORT_SHA', '--region', '$LOCATION']
  id: Deploy
