steps:
- name: node:12
  id: Install
  entrypoint: npm
  args: ['install']
- name: node:12
  id: Test
  entrypoint: npm
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/web:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'gcr.io/$PROJECT_ID/web:$SHORT_SHA']
