steps:
- name: node:14
  id: Install
  entrypoint: npm
  args: ['ci']
- name: node:14
  id: Test
  entrypoint: npm
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/api:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'eu.gcr.io/$PROJECT_ID/api:$SHORT_SHA']
